dist: bionic
language: cpp

jobs:
  include:
    - os: linux
      compiler: clang
      env: BTYPE=Release
    - os: linux
      compiler: gcc
      env: BTYPE=Release
    - os: osx
      compiler: clang
      env: BTYPE=Release
    - os: osx
      compiler: gcc
      env: BTYPE=Release

script:
  - make